--"Грязное" чтение. Транзакция Т2. Уровень изоляции "READ UNCOMMITTED"
USE TV_journalism
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION 
UPDATE EMPLOYEE
SET City_ID = '3'
WHERE EMPLOYEE.Employee_ID = '1'
ROLLBACK