SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION
UPDATE EMPLOYEE
SET City_ID = '3'
WHERE EMPLOYEE.Employee_ID = '1'
COMMIT

SELECT * FROM EMPLOYEE WHERE EMPLOYEE.Employee_ID = '1'