USE TV_journalism
GO

IF OBJECT_ID ('V2 ', 'V') IS NOT NULL  
DROP VIEW V2
GO


CREATE VIEW V2 AS  
SELECT EMPLOYEE.Last_Name, EMPLOYEE.Salary FROM EMPLOYEE
WHERE Salary > 2000
--WITH CHECK OPTION
GO

INSERT INTO V2 VALUES ('Сидоров', 1700); 
go

SELECT * FROM V2
GO
SELECT EMPLOYEE.Last_Name, EMPLOYEE.Salary FROM EMPLOYEE
WHERE EMPLOYEE.Last_Name = 'Сидоров'