--Удалить из базы данных  'Репортер'

IF OBJECT_ID ('FK_EMPLOYEE_JOB') IS NOT NULL  
ALTER TABLE EMPLOYEE  
DROP CONSTRAINT FK_EMPLOYEE_JOB;


ALTER TABLE EMPLOYEE ADD 
CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY(Job_ID) REFERENCES JOB(Job_ID)


DELETE FROM JOB
WHERE 
JOB.Job_Name = 'Репортер';


