--для каждой страны вывести города с максимальным числом работников
WITH CTE (COUNTRY_NAME,CITY_NAME,EMP_NUM)
AS (SELECT COUNTRY.Name,CITY.name, COUNT(DISTINCT EMPLOYEE.Employee_ID)
		FROM CITY 
		JOIN EMPLOYEE ON EMPLOYEE.City_ID = CITY.Сity_ID
		JOIN COUNTRY ON CITY.Сountry_ID = COUNTRY.Country_ID
		GROUP BY COUNTRY.Name,CITY.name),

MAX_CTE (COUNTRY_NAME,EMP_MAX)
AS (SELECT COUNTRY_NAME, MAX(CTE.EMP_NUM)
	FROM CTE
	GROUP BY COUNTRY_NAME)

SELECT MAX_CTE.COUNTRY_NAME as 'Страна',CITY_NAME AS 'Город', MAX_CTE.EMP_MAX as 'Число сотрудников' 
FROM MAX_CTE
JOIN CTE ON EMP_NUM = EMP_MAX AND CTE.COUNTRY_NAME = MAX_CTE.COUNTRY_NAME
