--Скомпоновать список сюжетов, их длительность, корреспондент для выпуска новостей в '20-00 3.3.2006'.

SELECT REPORTS.NAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SHOW.Name, Duration
FROM REPORTS
JOIN REPORT_REPORTER ON REPORT_REPORTER.Report_ID = REPORTS.Report_ID
JOIN EMPLOYEE ON EMPLOYEE.Employee_ID = REPORT_REPORTER.Reporter_ID
JOIN REPORTS_SHOW ON REPORTS_SHOW.Report_ID = REPORTS.Report_ID
JOIN SHOW ON REPORTS_SHOW.Show_ID = SHOW.SHOW_ID
WHERE  REPORTS_SHOW.Date = '03-03-2006 20:00:00'