--Корреспондент, страна, среднее время репортажа, среднее количество репортажей в месяц, средняя степень опасности репортажа.

WITH 

QUANT_MONTH (EMPL_ID, QUANT_MONTH)
AS
(
SELECT EMPLOYEE.Employee_ID, COUNT(DISTINCT MONTH(REPORTS.Date))
FROM
REPORT_REPORTER
JOIN EMPLOYEE ON (EMPLOYEE.Employee_ID = REPORT_REPORTER.Reporter_ID)
JOIN REPORTS ON (REPORT_REPORTER.Report_ID = REPORTS.Report_ID)
GROUP BY EMPLOYEE.Employee_ID
),

AVG_CTE (AVG_DURATION, AVG_DANGER, AVG_NUM, REP_ID)  
AS    
(  
SELECT CAST(CAST(AVG(CAST(CAST(REPORTS.Duration as datetime) as float)) as datetime) as time),
AVG(CAST(EVENT.DANGER as float)), COUNT(*), REPORT_REPORTER.Reporter_ID
FROM REPORTS
JOIN EVENT ON (EVENT.Event_ID =  REPORTS.Event_ID)
JOIN REPORT_REPORTER ON (REPORT_REPORTER.Report_ID = REPORTS.Report_ID)
GROUP BY REPORT_REPORTER.Reporter_ID
)


SELECT EMPLOYEE.First_Name, EMPLOYEE.Middle_Name, EMPLOYEE.Last_Name, COUNTRY.Name, AVG_CTE.AVG_NUM/QUANT_MONTH.QUANT_MONTH AS AVG_MONTH,
AVG_CTE.AVG_NUM, AVG_CTE.AVG_DURATION, AVG_CTE.AVG_DANGER
FROM EMPLOYEE
JOIN AVG_CTE ON AVG_CTE.REP_ID = EMPLOYEE.Employee_ID
JOIN QUANT_MONTH ON QUANT_MONTH.EMPL_ID = EMPLOYEE.Employee_ID
JOIN CITY ON EMPLOYEE.City_ID = CITY.Сity_ID
JOIN COUNTRY ON COUNTRY.Country_ID = CITY.Сountry_ID
ORDER BY COUNTRY.Name



