--Страна, тип события, количество корреспондентов, освещающих этот тип событий, среднее время в выпуске новостей, посвященное этому типу события.

WITH
AVG_TIME (TYPE_TIME,AVG_TIME, COUNTRY)
AS
(
SELECT EVENT_TYPE.Description, 
CAST(CAST(AVG(CAST(CAST(REPORTS.Duration as datetime) as float)) as datetime) as time),COUNTRY.Name
FROM  REPORTS
JOIN EVENT ON REPORTS.Event_ID = EVENT.Event_ID
JOIN EVENT_TYPE ON EVENT.Type_ID = EVENT_TYPE.TYPE_ID
JOIN CITY ON EVENT.Сity_ID = CITY.Сity_ID
JOIN COUNTRY ON COUNTRY.Country_ID = CITY.Сountry_ID
JOIN REPORTS_SHOW ON REPORTS.Report_ID = REPORTS_SHOW.Report_ID
JOIN SHOW ON REPORTS_SHOW.Show_ID = SHOW.SHOW_ID
WHERE SHOW.Name = 'Новости'
GROUP BY EVENT_TYPE.Description, COUNTRY.Name
),
EMP_NUM (TYPE_ENUM,NUM,COUNTRY)
AS
(
SELECT EVENT_TYPE.Description, COUNT(DISTINCT REPORT_REPORTER.Reporter_ID),COUNTRY.Name
FROM REPORTS
JOIN REPORT_REPORTER ON REPORT_REPORTER.Report_ID = REPORTS.Report_ID
JOIN EVENT ON REPORTS.Event_ID = EVENT.Event_ID
JOIN EVENT_TYPE ON EVENT.Type_ID = EVENT_TYPE.TYPE_ID
JOIN CITY ON EVENT.Сity_ID = CITY.Сity_ID
JOIN COUNTRY ON COUNTRY.Country_ID = CITY.Сountry_ID
GROUP BY EVENT_TYPE.Description, COUNTRY.Name
)


SELECT EMP_NUM.TYPE_ENUM,EMP_NUM.COUNTRY,EMP_NUM.NUM, AVG_TIME FROM EMP_NUM
JOIN AVG_TIME ON (AVG_TIME.TYPE_TIME = EMP_NUM.TYPE_ENUM) AND (AVG_TIME.COUNTRY = EMP_NUM.COUNTRY)






