--Фантом. Т1. Уровень изоляции REPEATABLE READ
USE TV_journalism
GO


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION 

SELECT * 
FROM EMPLOYEE
WHERE Salary > 2500

SELECT * 
FROM EMPLOYEE
WHERE Salary > 2500
COMMIT