--Повторяющееся чтение. Т2. Уровень изоляции REPEATABLE READ
USE TV_journalism
GO


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
UPDATE EMPLOYEE
SET City_ID = '3'
WHERE EMPLOYEE.Employee_ID = '1'
COMMIT