--Неповторяющееся чтение. Т1. Уровень изоляции REPEATABLE READ
USE TV_journalism
GO


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION 
SELECT * 
FROM EMPLOYEE
WHERE EMPLOYEE.Employee_ID = '1'

SELECT * 
FROM EMPLOYEE
WHERE EMPLOYEE.Employee_ID = '1'
COMMIT 