--"Грязное" чтение. Транзакция Т2. Уровень изоляции "READ COMMITTED"
USE TV_journalism
GO

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION 
UPDATE EMPLOYEE
SET City_ID = '3'
WHERE EMPLOYEE.Employee_ID = '1'
ROLLBACK