USE TV_journalism


IF OBJECT_ID ('FK_CITY_COUNTRY') IS NOT NULL  
ALTER TABLE CITY
DROP CONSTRAINT FK_CITY_COUNTRY;
IF OBJECT_ID ('FK_EMPLOYEE_JOB') IS NOT NULL  
ALTER TABLE EMPLOYEE  
DROP CONSTRAINT FK_EMPLOYEE_JOB;
IF OBJECT_ID ('FK_EMPLOYEE_SPEC') IS NOT NULL  
ALTER TABLE EMPLOYEE  
DROP CONSTRAINT FK_EMPLOYEE_SPEC;
IF OBJECT_ID ('FK_EMPLOYEE_CITY') IS NOT NULL  
ALTER TABLE EMPLOYEE
DROP CONSTRAINT FK_EMPLOYEE_CITY;
IF OBJECT_ID ('FK_EVENT_CITY') IS NOT NULL  
ALTER TABLE [EVENT]
DROP CONSTRAINT FK_EVENT_CITY;
IF OBJECT_ID ('FK_EVENT_TYPE') IS NOT NULL  
ALTER TABLE [EVENT]
DROP CONSTRAINT FK_EVENT_TYPE;
IF OBJECT_ID ('FK_REPORTS_EVENT') IS NOT NULL  
ALTER TABLE REPORTS
DROP CONSTRAINT FK_REPORTS_EVENT;
IF OBJECT_ID ('FK_RI_REPORTS') IS NOT NULL  
ALTER TABLE REPORTS_IMAGE
DROP CONSTRAINT FK_RI_REPORTS;
IF OBJECT_ID ('FK_RI_IMAGE') IS NOT NULL  
ALTER TABLE REPORTS_IMAGE
DROP CONSTRAINT FK_RI_IMAGE;
IF OBJECT_ID ('FK_RV_REPORTS') IS NOT NULL  
ALTER TABLE REPORTS_VIDEO
DROP CONSTRAINT FK_RV_REPORTS;
IF OBJECT_ID ('FK_RV_VIDEO') IS NOT NULL  
ALTER TABLE REPORTS_VIDEO
DROP CONSTRAINT FK_RV_VIDEO;
IF OBJECT_ID ('FK_SHOW_TA') IS NOT NULL  
ALTER TABLE SHOW
DROP CONSTRAINT FK_SHOW_TA;
IF OBJECT_ID ('FK_RS_REPORTS') IS NOT NULL  
ALTER TABLE REPORTS_SHOW
DROP CONSTRAINT FK_RS_REPORTS;
IF OBJECT_ID ('FK_RS_SHOW') IS NOT NULL  
ALTER TABLE REPORTS_SHOW
DROP CONSTRAINT FK_RS_SHOW;
IF OBJECT_ID ('FK_OA_ADVERTISER') IS NOT NULL  
ALTER TABLE ORDER_AD
DROP CONSTRAINT FK_OA_ADVERTISER;
IF OBJECT_ID ('FK_OA_SHOW') IS NOT NULL  
ALTER TABLE ORDER_AD
DROP CONSTRAINT FK_OA_SHOW;
IF OBJECT_ID ('FK_ANCHOR_EMPLOYEE') IS NOT NULL  
ALTER TABLE ANCHOR
DROP CONSTRAINT FK_ANCHOR_EMPLOYEE;
IF OBJECT_ID ('FK_ANCHOR_SHOW') IS NOT NULL  
ALTER TABLE ANCHOR
DROP CONSTRAINT FK_ANCHOR_SHOW;
IF OBJECT_ID ('FK_RR_REPORTER') IS NOT NULL  
ALTER TABLE REPORT_REPORTER
DROP CONSTRAINT FK_RR_REPORTER;
IF OBJECT_ID ('FK_RR_CAMERAMAN') IS NOT NULL  
ALTER TABLE REPORT_REPORTER
DROP CONSTRAINT FK_RR_CAMERAMAN;
IF OBJECT_ID ('FK_RR_REPORTS') IS NOT NULL  
ALTER TABLE REPORT_REPORTER
DROP CONSTRAINT FK_RR_REPORTS;


DROP TABLE IF EXISTS EMPLOYEE
DROP TABLE IF EXISTS JOB
DROP TABLE IF EXISTS SPECIALIZATION
DROP TABLE IF EXISTS CITY
DROP TABLE IF EXISTS TARGET_AUDIENCE
DROP TABLE IF EXISTS COUNTRY
DROP TABLE IF EXISTS EVENT_TYPE
DROP TABLE IF EXISTS [EVENT]
DROP TABLE IF EXISTS REPORTS
DROP TABLE IF EXISTS [IMAGE]
DROP TABLE IF EXISTS REPORTS_IMAGE
DROP TABLE IF EXISTS VIDEO
DROP TABLE IF EXISTS REPORTS_VIDEO
DROP TABLE IF EXISTS SHOW
DROP TABLE IF EXISTS REPORTS_SHOW
DROP TABLE IF EXISTS ADVERTISER
DROP TABLE IF EXISTS ORDER_AD
DROP TABLE IF EXISTS ANCHOR
DROP TABLE IF EXISTS REPORT_REPORTER


CREATE TABLE COUNTRY
(
Country_ID int IDENTITY(1,1) NOT NULL,
[Name] varchar(50) NOT NULL,
CONSTRAINT PK_COUNTRY PRIMARY KEY(Country_ID)
)

CREATE TABLE CITY 
(
Ñity_ID int IDENTITY(1,1) NOT NULL,
[name] varchar(50) NOT NULL,
Ñountry_ID int NOT NULL,
CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY(Ñountry_ID) REFERENCES COUNTRY(Country_ID),
CONSTRAINT PK_CITY PRIMARY KEY(Ñity_ID)
)

CREATE TABLE JOB
(
Job_ID int IDENTITY(1,1) NOT NULL,
Job_Name varchar(50) NOT NULL,
CONSTRAINT PK_JOB PRIMARY KEY(Job_ID)
)

CREATE TABLE SPECIALIZATION
(
Spec_ID int IDENTITY(1,1) NOT NULL,
Spec_Name varchar(50) NOT NULL,
CONSTRAINT PK_SPEC PRIMARY KEY(Spec_ID)
)

CREATE TABLE EMPLOYEE
(
Employee_ID int IDENTITY(1,1) NOT NULL,
First_Name varchar(30)  NULL,
Middle_Name varchar(50) NULL,
Last_Name varchar(50)  NULL,
Job_ID int  NULL,
City_ID int  NULL,
Spec_ID int NULL,
Salary smallmoney NOT NULL,
CONSTRAINT PK_EMPLOYEE PRIMARY KEY(Employee_ID),
CONSTRAINT FK_EMPLOYEE_CITY FOREIGN KEY(City_ID) REFERENCES CITY(Ñity_ID),
CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY(Job_ID) REFERENCES JOB(Job_ID),
CONSTRAINT FK_EMPLOYEE_SPEC FOREIGN KEY(Spec_ID) REFERENCES SPECIALIZATION(Spec_ID),
)

CREATE TABLE EVENT_TYPE
(
[TYPE_ID] int IDENTITY(1,1) NOT NULL,
[Description] varchar(100) NOT NULL,
CONSTRAINT PK_EVENT_TYPE PRIMARY KEY([Type_ID])
)

CREATE TABLE [EVENT] 
(
Event_ID int IDENTITY(1,1) NOT NULL,
[Name] varchar(100) NOT NULL,
[Date] date NOT NULL,
Ñity_ID int NULL,
[Type_ID] int NOT NULL,
Danger smallint NOT NULL,
CONSTRAINT FK_EVENT_CITY FOREIGN KEY(Ñity_ID) REFERENCES CITY(Ñity_ID),
CONSTRAINT FK_EVENT_TYPE FOREIGN KEY([Type_ID]) REFERENCES EVENT_TYPE([TYPE_ID]),
CONSTRAINT PK_EVENT PRIMARY KEY(Event_ID)
)

CREATE TABLE REPORTS
(
Report_ID int IDENTITY(1,1) NOT NULL,
[Name] varchar(200) NOT NULL,
[Date] date NOT NULL,
Duration time NOT NULL,
Event_ID int NOT NULL,
CONSTRAINT FK_REPORTS_EVENT FOREIGN KEY(Event_ID) REFERENCES [EVENT](Event_ID),
CONSTRAINT PK_REPORTS PRIMARY KEY(Report_ID)
)

CREATE TABLE [IMAGE]
(
Image_ID int IDENTITY(1,1) NOT NULL,
Resolution smallint NOT NULL,
[Description] varchar(100) NULL,
CONSTRAINT PK_IMAGE PRIMARY KEY(Image_ID)
)

CREATE TABLE REPORTS_IMAGE
(
Report_ID int NOT NULL,
Image_ID int NOT NULL,
CONSTRAINT PK_REPORTS_IMAGE PRIMARY KEY(Report_ID,Image_ID),
CONSTRAINT FK_RI_REPORTS FOREIGN KEY(Report_ID) REFERENCES REPORTS(Report_ID),
CONSTRAINT FK_RI_IMAGE FOREIGN KEY(Image_ID) REFERENCES [IMAGE](Image_ID),
)

CREATE TABLE VIDEO
(
Video_ID int IDENTITY(1,1) NOT NULL,
Duration time NOT NULL,
Resolution smallint NOT NULL,
[Source] varchar(100) NULL,
CONSTRAINT PK_VIDEO PRIMARY KEY(Video_ID)
)

CREATE TABLE REPORTS_VIDEO
(
Report_ID int NOT NULL,
Video_ID int NOT NULL,
CONSTRAINT PK_REPORTS_VIDEO PRIMARY KEY(Report_ID,Video_ID),
CONSTRAINT FK_RV_REPORTS FOREIGN KEY(Report_ID) REFERENCES REPORTS(Report_ID),
CONSTRAINT FK_RV_VIDEO FOREIGN KEY(Video_ID) REFERENCES VIDEO(Video_ID),
)

CREATE TABLE TARGET_AUDIENCE
(
Target_audience_ID int IDENTITY(1,1) NOT NULL,
AVG_Age smallint NOT NULL,
[Description] varchar(100) NULL,
CONSTRAINT PK_Target_audience PRIMARY KEY(Target_audience_ID)
)

CREATE TABLE SHOW
(
SHOW_ID int IDENTITY(1,1) NOT NULL,
[Name] varchar(30) NOT NULL,
[Start_Date] date NOT NULL,
[End_Date] date NULL,
Age_limit smallint NOT NULL,
Raiting smallint NOT NULL,
Target_audience_ID int NOT NULL,

CONSTRAINT PK_SHOW PRIMARY KEY(Show_ID),
CONSTRAINT FK_SHOW_TA FOREIGN KEY(Target_audience_ID) REFERENCES TARGET_AUDIENCE(Target_audience_ID),
)

CREATE TABLE REPORTS_SHOW
(
Report_ID int NOT NULL,
Show_ID int NOT NULL,
[Date] smalldatetime NOT NULL,
CONSTRAINT PK_REPORTS_SHOW PRIMARY KEY(Report_ID,Show_ID,[Date]),
CONSTRAINT FK_RS_REPORTS FOREIGN KEY(Report_ID) REFERENCES REPORTS(Report_ID),
CONSTRAINT FK_RS_SHOW FOREIGN KEY(Show_ID) REFERENCES SHOW(Show_ID),
)

CREATE TABLE ADVERTISER
(
Advertiser_ID int IDENTITY(1,1) NOT NULL,
[Name] varchar(30) NOT NULL,
[Description] varchar(100) NULL,
Telephone varchar(15) NOT NULL,
E_mail varchar(50) NOT NULL,
CONSTRAINT PK_ADVERTISER PRIMARY KEY(Advertiser_ID)
)

CREATE TABLE ORDER_AD
(
Advertiser_ID int NOT NULL,
Quantity smallint NOT NULL,
[Start_date] date NOT NULL,
End_Date date NOT NULL,
Video_ID int NULL,
Show_ID int NOT NULL,
[Description] varchar(100) NULL,
CONSTRAINT PK_ORDER_AD PRIMARY KEY(Advertiser_ID,[Start_date],Show_ID),
CONSTRAINT FK_OA_ADVERTISER FOREIGN KEY(Advertiser_ID) REFERENCES ADVERTISER(Advertiser_ID),
CONSTRAINT FK_OA_SHOW FOREIGN KEY(Show_ID) REFERENCES SHOW(Show_ID),
)

CREATE TABLE ANCHOR
(
Employee_ID int NOT NULL,
Show_ID int NOT NULL,
CONSTRAINT PK_ANCHOR PRIMARY KEY(Employee_ID,Show_ID),
CONSTRAINT FK_ANCHOR_EMPLOYEE FOREIGN KEY(Employee_ID) REFERENCES EMPLOYEE(Employee_ID),
CONSTRAINT FK_ANCHOR_SHOW FOREIGN KEY(Show_ID) REFERENCES SHOW(Show_ID),
)

CREATE TABLE REPORT_REPORTER
(
Report_ID int NOT NULL,
Reporter_ID int NOT NULL,
Cameraman_ID int NOT NULL,
CONSTRAINT PK_RR PRIMARY KEY(Report_ID, Reporter_ID, Cameraman_ID),
CONSTRAINT FK_RR_REPORTER FOREIGN KEY(Reporter_ID) REFERENCES EMPLOYEE(Employee_ID),
CONSTRAINT FK_RR_CAMERAMAN FOREIGN KEY(Cameraman_ID) REFERENCES EMPLOYEE(Employee_ID),
CONSTRAINT FK_RR_REPORTS FOREIGN KEY(Report_ID) REFERENCES REPORTS(Report_ID),
)